config/routes.rb
Rails.application.routes.draw do
  root 'calculator#index'
  post 'calculate', to: 'calculator#calculate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  def index
  end

  def calculate
    @first_number = params[:first_number].to_f
    @second_number = params[:second_number].to_f
    @operator = params[:operator]

    @result = case @operator
              when '+' then @first_number + @second_number
              when '-' then @first_number - @second_number
              when '*' then @first_number * @second_number
              when '/' then @second_number != 0 ? @first_number / @second_number : 'Error: Division by zero'
              else 'Invalid operation'
              end
    
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/views/calculator/index.html.erb
<h1>Simple Calculator</h1>
<%= form_with url: calculate_path, method: :post, local: true do |form| %>
  <div>
    <%= form.label :first_number, "First Number:" %>
    <%= form.number_field :first_number, step: :any %>
  </div>
  
  <div>
    <%= form.label :operator, "Operator:" %>
    <%= form.select :operator, ['+', '-', '*', '/'] %>
  </div>
  
  <div>
    <%= form.label :second_number, "Second Number:" %>
    <%= form.number_field :second_number, step: :any %>
  </div>
  
  <div>
    <%= form.submit "Calculate" %>
  </div>
<% end %>

<% if @result.present? %>
  <h2>Result: <%= @result %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>